### PR TITLE
O sorensen issue 11 1

### PR DESCRIPTION
**Pull request by OSoerensen**
Pull request based on Issue 11 created by Brian Buffet

### CODE REVIEW

**Comment by OSoerensen** [comment]
Thank you @fernandohandball for spotting the missing training, this is added now in this new pull request

**Review by fernandohandball — COMMENTED** [review]
@OSoerensen ,

Thanks for updating the file. I see one pending step before publishing the file: 

The same summary description is available in two courses i.e. 'Recoding:transforming...' and 'Data collection with XLSX Templates...'. We should:
Course entitled 'Recoding: Transforming Data into Different Structures'
- Delete the summary which reads 'statistical agencies, central banks...' 
Course entitled 'Data Collection with XLSX Templates: All about XLSX Templates'
- Replace the summary info with the one that was deleted above i.e. ' which reads 'statistical agencies, central banks...'

**Comment by OSoerensen** [comment]
Thank you again @fernandohandball for spotting the mistake, I have tried again

**Comment by OSoerensen** [comment]
Closing this one and creating one single pull request for the last 3 courses

**Pull request closed without merging**
